# Generated by Django 2.2.9 on 2020-02-10 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='money',
            name='category',
            field=models.CharField(default='食費', max_length=10),
            preserve_default=False,
        ),
    ]
