# Generated by Django 2.2.9 on 2020-02-13 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0003_auto_20200212_1620'),
    ]

    operations = [
        migrations.CreateModel(
            name='Money',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('use_date', models.DateField(verbose_name='日付')),
                ('detail', models.CharField(max_length=200)),
                ('cost', models.IntegerField(default=0)),
                ('category', models.CharField(max_length=10)),
            ],
        ),
    ]
