# Generated by Django 2.2.9 on 2020-02-13 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0004_money'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExpenditureDetail',
        ),
        migrations.DeleteModel(
            name='ReceiptImage',
        ),
    ]
